blog/urls.py
from django.urls import path

from .views import PostListView, post_list, post_detail, post_share, post_search

from .feeds import latestPostFeed

app_name = "blog"

urlpatterns = [
  path('', post_list, name="post_list"),
  # path('', PostListView.as_view(), name='post_list'),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
  path('<int:post_id>/share/', post_share, name="post_share"),
  path('tag/<slug:tag_slug>/', post_list, name="post_list_by_tag"),
  path('feed/', latestPostFeed(), name='post_feed'),
  path('search/', post_search, name="post_search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
  def get_queryset(self):
    return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
  STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
  )

  title = models.CharField(max_length=250)
  slug = models.SlugField(max_length=250, unique_for_date='publish')
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
  body = models.TextField()
  publish = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

  class Meta:
    ordering=('-publish',) # Descending order (newest to oldest)

  def __str__(self):
    return self.title

  objects = models.Manager()      # The default manager
  published = PublishedManager()  # Our Custom manager
  tags = TaggableManager()        # The tags manager will allow you to add, retrieve, and remove tags from Post objects

  @property
  def date_diff(self):
    return f"{str(timezone.now() - self.publish).split(':')[0]} hours ago."

  def get_absolute_url(self):
    return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
  name = models.CharField(max_length=80)
  email = models.EmailField()
  body = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True)

  class Meta:
    ordering=('created',)

  def __str__(self):
    return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
  name = forms.CharField(max_length=25)
  email = forms.EmailField()
  to = forms.EmailField()
  comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ('name', 'email', 'body') 


class SearchForm(forms.Form):
  query = forms.CharField()

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count
from django.contrib.postgres.search import SearchRank, SearchVector, SearchQuery, TrigramSimilarity
from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

class PostListView(ListView):  
  queryset = Post.published.all()
  context_object_name = 'posts'
  paginate_by = 3
  template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
  object_list = Post.objects.all()
  tag = None

  if tag_slug:
    tag = get_object_or_404(Tag, slug=tag_slug)
    object_list = Post.objects.filter(tags__in=[tag])

  paginator = Paginator(object_list, 3)  # 3 objects per page
  page = request.GET.get('page')

  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    # if the page is not an integer deliver the first page
    posts = paginator.page(1)
  except EmptyPage:
    # if page is out of range deliver last page of results
    posts = paginator.page(paginator.num_pages)

  # posts = Post.published.all()
  return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):
  post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

  # List of active comments for this post  
  comments = post.comments.filter(active=True)
  
  new_comment = None

  if request.method == "POST":
    # A comment was posted
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      # Create comment object but don't save to database yet
      new_comment = comment_form.save(commit=False)
      # Assign the current post to the comment
      new_comment.post = post
      # Save the comment to the database
      new_comment.save()
  else:
    comment_form = CommentForm()

  if post.tags.count() > 1:
    tags = list(post.tags.all())
    tags.pop() # remove default slug prepoulated tag
    # print(post.slug, type(post.slug))
  else:
    tags = post.tags.all()

  # List of similar posts
  post_tags_ids = post.tags.values_list('id', flat=True)
  similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
  similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

  return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'tags': tags, 'similar_posts': similar_posts})

def post_share(request, post_id):
  # Retrieve post by id
  post = get_object_or_404(Post, id=post_id, status='published')
  sent = False

  if request.method == 'POST':
    # Form was submitted
    form = EmailPostForm(request.POST)
    if form.is_valid():
      # Form fields passed validation
      cd = form.cleaned_data
      # ...Send email
      post_url = request.build_absolute_uri(post.get_absolute_url())
      subject = f"{cd['name']} recommends you read {post.title}"
      message = f"Read {post.title} at {post_url}\n\n{cd['name']} comments: {cd['comments']}"

      send_mail(subject, message, 'medhatusama@gmail.com', [cd['to']])
      sent = True

  else:
    form = EmailPostForm()
  return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

def post_search(request):
  form = SearchForm()
  query = None
  results = []
  if 'query' in request.GET:
    form = SearchForm(request.GET)
    if form.is_valid():
      query = form.cleaned_data['query']
      # results = Post.published.annotate(search=SearchVector('title', 'body')).filter(search=query)
      # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
      # results = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
      # Search using stemming algorithm
      search_vector = SearchVector('title', 'body')
      search_query = SearchQuery(query)
      results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by("-rank")

  return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css'%}" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <style>
      body {
        background-color: #ffffff;
        opacity: 0.8;
        background-image:  radial-gradient(#00a1ff 0.5px, transparent 0.5px), radial-gradient(#00a1ff 0.5px, #ffffff 0.5px);
        background-size: 20px 20px;
        background-position: 0 0,10px 10px;
      }
    </style>
  </head>
  <body>
    <div id="content">
      {% block content %} {% endblock %}
    </div>
    <div id="sidebar">
      <h2>My blog</h2>
      <p>This is my blog. I've written <span class="badge badge-info badge-pill">{% total_posts %}</span> posts so far.</p>
      <p>
        <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
      </p>
      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}
      <h3>Most commented posts</h3>
      {% get_most_commented_posts 3 as most_commented_posts %}
      <ul class="list-group">
        {% for post in most_commented_posts %}
          <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            <span class="badge badge-info badge-pill">{{ post.comments.count }} comment{{ post.comments.count|pluralize }}</span>
          </li>
         {% empty %} No posts yet.
        {% endfor%}
      </ul>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="tags badge badge-pill badge-secondary">Tags: {{ tags|join:", "}}</p>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }} 
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
  </p>

  <h2>Similar Posts</h2>
  {% for post in similar_posts %}
    <p>
      <a class="badge badge-dark"href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
  <p>There are no similar posts yet.</p> 
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}

  {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  <hr style="color: #bbb; background-color: #bbb"/>
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form method="post">
      <div class="form-group">
        {{ comment_form|crispy }}
        {% csrf_token %}
      </div>
      <p><input class="btn btn-primary my-3" type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
{% load blog_tags %}

<ul class="list-group">
  {% for post in latest_posts %}
    <li class="list-group-item list-group-item-action list-group-item-{% rcolor forloop.counter0 %} d-flex justify-content-between align-items-center">
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      <small>{{ post.date_diff }}</small>
    </li>
    {% empty %} No posts yet.
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My blog</h1>
  <div class="row">
    <div class="col-lg-12">
      <a class="btn btn-dark btn-sm float-right" href="{% url 'blog:post_search' %}">Search</a>
    </div>
  </div>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %} 
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
    <p class="tags badge badge-pill badge-light">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {% if forloop.first or not forloop.last %}
          {{ tag.name }}
          {% endif %}
        </a>
        <!-- {% if not forloop.last %}, {% endif %} -->
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }} 
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  <!-- page_obj -->
  {% include "pagination.html" with page=posts %} 
{% endblock %} 

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results%}
      <h4>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {% csrf_token %}
      <div class="form-group">
        {{ form|crispy }}
        <input class="btn btn-primary mt-3" type="submit" value="Search">
      </div>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Share a post{% endblock %}
 
{% block content %}
  {% if sent %}
    <h1>Email was sent successfully</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to}}
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        {{ form|crispy }}
        <input class="btn btn-primary mt-3" type="submit" value="Send e-mail">
      </div>
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a class="" href="?page={{ page.next_page_number}}">Next</a>
    {% endif %}
  </span>
</div>